
## BUILD AUDIT PROJECT
FROM node:18.14-alpine AS build
WORKDIR /dist/src/app
RUN npm cache clean --force
COPY . .
RUN npm install --force
RUN npm run build-proxy --prod
FROM nginx:latest AS ngi
COPY --from=build /dist/src/app/dist /usr/share/nginx/html
COPY /nginx-proxy.conf  /etc/nginx/conf.d/default.conf
EXPOSE 80