export const environment = {
    production: true,
    version: 'test',
    menu_key: 'routerLink',
    //menu_key: 'proxy_link',
    //menu_key: 'routerLink',
    domain: 'https://ewo.acacy.com.vn/',
    apiUrl: 'https://audit-api.acacy.vn/api/',
    api_authenticate: 'https://ewo-api.acacy.vn/api/',
    api_EWO_Attendance: 'https://attendance-api.acacy.vn/api/',
    api_EWO_Survey: 'https://survey-api.acacy.vn/api/',
    api_file: 'https://files-api.acacy.vn/api/',
    api_EWO_POSM: 'https://posm-api.acacy.vn/api/',
    api_EWO_OSA: 'https://osa-api.acacy.vn/api/',
    api_EWO_DISPLAY: 'https://display-api.acacy.vn/api/',
    api_EWO_WORKFOLLOW: 'https://workfollow-api.acacy.vn/api/',
    api_EWO_WAREHOUSE: 'https://warehouse-api.acacy.vn/api/',
    api_EWO_SELL: 'https://sell-api.acacy.vn/api/',
    api_EWO_OOL: 'https://ool-api.acacy.vn/api/',
    api_EWO_Activation: 'https://activation-api.acacy.vn/api/',
    api_EWO_Logistics: 'https://logistics-api.acacy.vn/api/',
    api_EWO_Inventory: 'https://inventory-api.acacy.vn/api/',
    api_EWO_SOS: 'https://sos-api.acacy.vn/api/',
    api_EWO_FIELDCOACHING: 'https://fieldcoaching-api.acacy.vn/api/',
    project_id: 0,
    url_login: '/login/',
    url_redirect_proxy: '/request/'
};
